function GenerateSafetyFigures()
%GENERATESAFETYFIGURES  Reproduce all MI safety figures from the .hws files.
%
%   Figure 1  L11-5 pulse-inversion: MI vs TX voltage for pos/neg pulse,
%             50/1e6 ohm (corrected + uncorrected) + Verasonics reference.
%             (generated by PlotMI_L11_5.m)
%   Figure 2  S5-1 focused imaging (79 mm): MI vs axial depth (local lateral+
%             elevation max at each depth) and MI vs TX voltage at the peak.
%   Figure 3  S5-1 push, 79 elements: same two panels.
%   Figure 4  S5-1 push, 61 elements: same two panels.
%
%   All MI values are DERATED (0.3 dB/cm/MHz). Depth of every point is the
%   distance from Home (= transducer centre) to that point. Peak voltages are
%   converted to pressure with the Onda parallel-circuit sensitivity
%   (HydrophoneTables.mat), identical to CalculateSafety.m; all S5-1 data are
%   50 ohm so no load correction is applied. The MI-vs-voltage panels
%   extrapolate the unsaturated (linear) region to the MI = 1.9 limit.
%
%   Just run:  GenerateSafetyFigures
%   Requires readHWS.m and PlotMI_L11_5.m on the path (auto-added below).

    base  = miData('S5-1','2026-08-13_sessionA_preamp_50ohm');
    addpath(fileparts(mfilename('fullpath')));  % co-located analysis code
    outdir = miRoot('results'); if ~exist(outdir,'dir'), mkdir(outdir); end

    % ---- Figure 1: L11-5 (existing generator) ----
    try
        PlotMI_L11_5();   % writes MI_vs_TXvoltage_L11_5_realigned.png
        fprintf('Figure 1 (L11-5) generated by PlotMI_L11_5.\n');
    catch e
        warning('PlotMI_L11_5 failed: %s', e.message);
    end

    % ---- Figures 2-4: S5-1 ----
    datasets = {
      'S5-1 focused imaging (79 mm)', ...
        'focused_imaging_axial',                 'S5-1_10V_50ohm_pos_foc_%d.hws',      1:15, ...
        'focused_imaging_sweep',       'S5-1_%dV_50ohm_pos_foc.hws',         [2 4 6 8 10 12 15 20];
      'S5-1 push, 79 elements', ...
        'push_79el_axial',         'S5-1_5V_50ohm_fund_push_%d.hws',     1:16, ...
        'push_79el_sweep','S5-1_%dV_50ohm_fund_push.hws',     [2 3 4 5 6 7 8 9 10 11 12];
      'S5-1 push, 61 elements', ...
        'push_61el_axial',         'S5-1_5V_50ohm_fund_push_61el_%d.hws',1:13, ...
        'push_61el_sweep','S5-1_%dV_50ohm_fund_push_61el__opt.hws',[3 4 6 7 8]};

    for r = 1:size(datasets,1)
        name   = datasets{r,1};
        axDir  = fullfile(base, datasets{r,2}); axPat = datasets{r,3}; axK = datasets{r,4};
        vDir   = fullfile(base, datasets{r,5}); vPat = datasets{r,6}; vV = datasets{r,7};
        makeFigure(name, axDir, axPat, axK, vDir, vPat, vV, outdir);
    end
    fprintf('\nAll figures saved to: %s\n', outdir);
end

% ===================================================================
function makeFigure(name, axDir, axPat, axK, vDir, vPat, vV, outdir)
    Home = [-82.21 105.14 -42.90];              % transducer centre [mm]

    % --- axial scan: derated MI vs depth (per-point depth & derating) ---
    fawf = measureFawf(fullfile(axDir, sprintf(axPat, axK(round(end/2)))));
    sens = sensVperMPa(fawf);
    dep = nan(numel(axK),1); MIax = nan(numel(axK),1);
    for i = 1:numel(axK)
        [Vpk, pos] = readVpkPos(fullfile(axDir, sprintf(axPat, axK(i))));
        dep(i)  = norm(pos - Home);
        MIax(i) = Vpk / sens / derate(dep(i), fawf) / sqrt(fawf);
    end
    [dep, o] = sort(dep); MIax = MIax(o);
    [MImax, ip] = max(MIax);

    % --- voltage sweep at the peak: derated MI vs TX voltage ---
    fawfV = measureFawf(fullfile(vDir, sprintf(vPat, vV(1))));
    sensV = sensVperMPa(fawfV);
    Vpk = nan(numel(vV),1); MIv = nan(numel(vV),1); depV = nan;
    for i = 1:numel(vV)
        [Vpk(i), pos] = readVpkPos(fullfile(vDir, sprintf(vPat, vV(i))));
        if isnan(depV), depV = norm(pos - Home); end
        MIv(i) = Vpk(i) / sensV / derate(depV, fawfV) / sqrt(fawfV);
    end
    [p, Vsat] = fitLinear(vV(:), MIv);          % linear fit over unsaturated V
    Vlim = (1.9 - p(2)) / p(1);                 % TX voltage at MI = 1.9

    % --- plot ---
    fig = figure('Color','w','Position',[80 80 980 420]);
    subplot(1,2,1); hold on; grid on; box on
    plot(dep, MIax, 'o-', 'LineWidth',1.5, 'MarkerFaceColor','w');
    plot(dep(ip), MImax, 'p', 'MarkerSize',15, 'MarkerFaceColor',[0.85 0.33 0.10], 'MarkerEdgeColor','k');
    xlabel('axial distance from transducer (mm)'); ylabel('MI (derated)');
    title(sprintf('%s\nMI vs axial (local lateral+elev. max), f_{awf}=%.2f MHz', name, fawf));
    text(dep(ip), MImax, sprintf('  peak %.3f @ %.0f mm', MImax, dep(ip)), 'FontSize',9);

    subplot(1,2,2); hold on; grid on; box on
    Vx = 0:0.5:max(Vlim*1.05, max(vV)+2); yl = [0 2.05];
    % shade the saturated region excluded from the extrapolation fit
    patch([Vsat Vx(end) Vx(end) Vsat], [yl(1) yl(1) yl(2) yl(2)], [0.55 0.55 0.55], ...
        'FaceAlpha',0.15, 'EdgeColor','none', 'DisplayName','excluded (saturation)');
    yline(1.9, 'k-', 'LineWidth',1.8, 'DisplayName','MI limit 1.9');
    plot(Vx, polyval(p,Vx), '--', 'Color',[0.85 0.33 0.10], 'LineWidth',1.4, 'HandleVisibility','off');
    plot(vV, MIv, 'o', 'MarkerFaceColor',[0.85 0.33 0.10], 'MarkerEdgeColor',[0.6 0.2 0.05], ...
        'MarkerSize',7, 'DisplayName','measured');
    plot(Vlim, 1.9, 'p', 'MarkerSize',15, 'MarkerFaceColor',[0.2 0.5 0.2], 'MarkerEdgeColor','k', ...
        'DisplayName',sprintf('MI=1.9 @ %.1f V', Vlim));
    xlabel('TX voltage (V)'); ylabel('MI (derated)');
    title(sprintf('MI vs TX voltage at peak (depth %.0f mm)\ndashed = linear extrap. of unsaturated V', depV));
    legend('Location','northwest'); ylim(yl); xlim([0 Vx(end)]);

    fn = fullfile(outdir, ['MI_' matlab.lang.makeValidName(name) '.png']);
    exportgraphics(fig, fn, 'Resolution', 150);
    fprintf('%-28s peak MI@10V=%.3f @ %.0fmm | MI=1.9 @ %.1f V  -> %s\n', ...
        name, MImax, dep(ip), Vlim, fn);
end

% ===================================================================
function [Vpk, pos] = readVpkPos(file)
    [w, cfg] = readHWS(file);
    Vpk = -min(w(1).y - median(w(1).y));
    t = regexp(cfg.notes, 'Pos\s*=\s*\(\s*([-\d.]+)\s*,\s*([-\d.]+)\s*,\s*([-\d.]+)', 'tokens', 'once');
    pos = [str2double(t{1}) str2double(t{2}) str2double(t{3})];
end

function fawf = measureFawf(file)
%MEASUREFAWF  IEC -6 dB centre of the fundamental (band 1.3-3.5 MHz) [MHz].
    w = readHWS(file); y = w(1).y - median(w(1).y); dt = w(1).dt;
    Y = abs(fft(y.*hann(numel(y)))); f = (0:numel(Y)-1)'/(numel(Y)*dt);
    hb = 1:floor(numel(Y)/2); fh = f(hb); Yh = Y(hb);
    bf = fh>1.3e6 & fh<3.5e6; pk = max(Yh.*bf); idx = find(Yh>=pk/2 & bf);
    fawf = (fh(idx(1)) + fh(idx(end)))/2 / 1e6;
end

function s = sensVperMPa(ft)
%SENSVPERMPA  Onda parallel-circuit loaded sensitivity [V/MPa] at ft [MHz].
    persistent HT AT
    if isempty(HT)
        S = load(miRoot('calibration','HydrophoneTables.mat'), ...
                 'AmplifierTable','HydrophoneTable');
        HT = S.HydrophoneTable; AT = S.AmplifierTable;
    end
    ih = find(HT.FREQ_MHz >= ft, 1); sh = db2mag(HT{ih,"SENS_DB"})*1e6; ch = HT{ih,"CAP_PF"}*1e-12;
    ia = find(AT.FREQ_MHZ >= ft, 1); ga = db2mag(AT{ia,"GAIN_DB"});     ca = AT{ia,"CAP_PF"}*1e-12;
    s = ga * sh * ch/(ca+ch) * 1e6;
end

function d = derate(depth_mm, ft)
    d = db2mag(0.3 * depth_mm/10 * ft);       % 0.3 dB/cm/MHz -> amplitude factor
end

function [p, Vsat] = fitLinear(V, MI)
%FITLINEAR  Linear fit of MI vs V over the unsaturated region.
%   Saturation onset = V where MI/V drops >5% below its peak for two
%   consecutive voltages (robust to single noisy points).
    r = MI ./ V; [rmax, im] = max(r); Vsat = max(V) + 1;
    for k = im+1:numel(V)
        if r(k) < 0.95*rmax && (k==numel(V) || r(k+1) < 0.95*rmax), Vsat = V(k); break; end
    end
    m = V < Vsat & V >= min(V);
    if nnz(m) < 2, m = true(size(V)); end
    p = polyfit(V(m), MI(m), 1);
end
